# Generated by Django 6.0.2 on 2026-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaaa', '0004_profile_experience_level_profile_preferred_yoga_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_yoga_type',
            new_name='favorite_style',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Новичок (первые шаги)'), ('MEDIUM', 'Продолжающий (базовый уровень)'), ('ADVANCED', 'Продвинутый (мастер практики)')], default='BEGINNER', max_length=20),
        ),
    ]
