# Generated by Django 6.0.2 on 2026-06-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaaa', '0003_alter_cart_user_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('BEGINNER', 'Новичок (первые шаги)'), ('INTERMEDIATE', 'Средний (уверенная практика)'), ('ADVANCED', 'Продвинутый (мастер)')], default='BEGINNER', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_yoga_type',
            field=models.CharField(blank=True, default='Хатха-йога', max_length=100),
        ),
    ]
